version: "3.8"
services:
  springbootdocker:
    image: tomcat:9.0.35-jdk11-openjdk-slim
    volumes:
      - "./web/static:/usr/local/tomcat/webapps/ROOT"
      - "./api/build/libs/ExamSpringBootDemo-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/api.war"
    ports:
      - "4444:8080"
